<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ForgotPasswordLink</name>
   <tag></tag>
   <elementGuidId>53cbe901-8c2c-4ad0-93eb-b2928d70b2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;/forgot_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;/forgot_password&quot;]</value>
   </webElementProperties>
</WebElementEntity>
