<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PipelinerLogo</name>
   <tag></tag>
   <elementGuidId>1cce714f-3cec-4134-a33f-e0c34462c430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ppl-icon[@class=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ppl-icon[@class=&quot;logo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
