<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResetPricesIcon</name>
   <tag></tag>
   <elementGuidId>dd3599a4-8001-4a68-9815-25fcab61231d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ppl-icon[@svgicon=&quot;color-reload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ppl-icon[@svgicon=&quot;color-reload&quot;]</value>
   </webElementProperties>
</WebElementEntity>
